### ISSUE TITLE
LEDs

### ISSUE THREAD

**Issue by xtacocorex** [KoljaWindeler/CHIP_ONION#1]
JKW, I was looking over the schematic and saw a possible issue in the design of the LED circuitry.

Since the LEDs on P0 and P3 are attached to 3V3 lines, should these 2 signals go to 3V3 instead of VCC?
I'm not sure about RELAY_LO since that comes out of the MOSFET attached to P0, but I'm thinking it may also need to go to 3V3.

**Comment by KoljaWindeler** [comment]
Yep that's a valid point, so even if you set the pin to "high" on the CHIP, it will still just go to 3.3V and not to 5V and since Vcc is 5V we'll still have 1.7V across the LED. Not enough to make it light up but it not the most energy efficient solution. I guess 3.3V would be better. That being said: There is a bug in the routing :) look really closely to 30.85/27.20 and you'll see that the VCC line for the LED is not connect :( 
I've simply soldered a little jumper from the unused pads of D1 to the header right above it (from 31.45/36.05 to 28.50/40.30) to fix that on my board. So if you want 3.3V diodes just jumper it over to e.g. 37.1/19.1 

I'll still change that for version 2!

Relay LO will be floating if the P0 is low, so there is no issue. Actually connecting the Relay to 3.3V would cause some trouble, because i doubt that the chip can supply that much current. 
Thats for letting me know
Kolja

**Comment by KoljaWindeler** [comment]
Fixed in 4dd7b1a6073f6ebdae83816fe5925f4ffa911943

**Comment by xtacocorex** [comment]
Yeah, I think I see it in my clone of the repo, that top pin of D1 should be tied to VCC, but there is no route to connect it.

Thanks for looking into this! :)
